DROP DATABASE IF EXISTS quanly;
CREATE DATABASE quanly;
USE quanly;

CREATE TABLE Department(
DepartmentID	INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DepartmentName	CHAR (10) NOT NULL UNIQUE
);

CREATE TABLE Position (
PositionID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
PositionName	ENUM ('DEV','TEST','SCRUM MASTER','PM') NOT NULL 
);

CREATE TABLE `Account` (
AccountID		 TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Email			VARCHAR(50) NOT NULL UNIQUE,
Username		VARCHAR(50)NOT NULL UNIQUE,
FullName		VARCHAR(50)NOT NULL,
DepartmentID	TINYINT UNSIGNED NOT NULL,
PositionID		TINYINT UNSIGNED NOT NULL,
CreateDate		DATE DEFAULT(now())
);

CREATE TABLE `Group` (
GroupID			INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
GroupName		VARCHAR(50)NOT NULL UNIQUE,
CreatorID		INT UNSIGNED,
CreateDate		DATETIME
);

CREATE TABLE GroupAccount (
GroupID			INT UNSIGNED NOT NULL UNIQUE,
AccountID		INT UNSIGNED NOT NULL UNIQUE,
JoinDate		DATETIME DEFAULT (NOW())
);

CREATE TABLE TypeQuestion (
TypeID			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
TypeName		ENUM ('ESSAY','MULTIPLE_CHOICE') NOT NULL UNIQUE
);

CREATE TABLE CategoryQuestion (
CategoryID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
CategoryName	VARCHAR(50)NOT NULL UNIQUE
);

CREATE TABLE Question (
QuestionID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Content			VARCHAR(50)NOT NULL,
CategoryID		TINYINT UNSIGNED NOT NULL,
TypeID			TINYINT UNSIGNED NOT NULL,
CreatorID		TINYINT UNSIGNED NOT NULL,
CreateDate		DATETIME DEFAULT (NOW())
);

CREATE TABLE Answer (
AnswerID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Content			VARCHAR(50) NOT NULL,
QuestionID		TINYINT UNSIGNED NOT NULL,
isCorrect		BOOLEAN
);

CREATE TABLE Exam (
ExamID			TINYINT AUTO_INCREMENT PRIMARY KEY,
`Code`			VARCHAR (50)NOT NULL,
Title			VARCHAR(50)NOT NULL,
CategoryID		TINYINT UNSIGNED NOT NULL,
Duration		TINYINT UNSIGNED NOT NULL,
CreatorID		TINYINT NOT NULL,
CreateDate		DATETIME DEFAULT (NOW())
);

CREATE TABLE ExamQuestion (
ExamID			TINYINT UNSIGNED NOT NULL,
QuestionID		TINYINT UNSIGNED NOT NULL
);


